<?php
/**
 * Created by PhpStorm.
 * User: ocean
 * Date: 18-3-5
 * Time: 下午3:10
 */

namespace app\admin\model;

use think\Model;
//use think\Session;
//use think\Cookie;


class Address extends Model
{
    protected $table = 'shop_address';

    /**
     * 初始化
     */
    protected static function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }
}