<?php
/**
 * Created by PhpStorm.
 * User: ocean
 * Date: 18-1-16
 * Time: 下午6:26
 */
namespace app\admin\model;

use think\Model;
use think\Session;
use think\Cookie;


class Cate extends Model
{
    protected $table = 'shop_cate';

    /**
     * 初始化
     */
    protected static function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }
}