<?php
/**
 * Created by PhpStorm.
 * User: ocean
 * Date: 18-3-5
 * Time: 上午10:48
 */

namespace app\admin\model;

use think\Model;
//use think\Session;
//use think\Cookie;


class ShopCar extends Model
{
    protected $table = 'shop_shopCar';

    /**
     * 初始化
     */
    protected static function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }
}