<?php
/**
 * Created by PhpStorm.
 * User: ocean
 * Date: 18-1-16
 * Time: 下午6:20
 */

namespace app\admin\model;

use think\Model;
use think\Session;
use think\Cookie;


class User extends Model
{
    protected $table = 'shop_user';

    /**
     * 初始化
     */
    protected static function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }

    /**
     * 检查是否登录状态
     * @return bool
     */
    public static function check_is_login()
    {
        if (Session::has('userName') || Cookie::has('userName')) {
            return true;
        } else {
            return false;
        }
    }

    /**
     * 验证登录
     * @param $verify
     * @return string
     */
    public static function check_login($data)
    {
        if (!captcha_check($data['verify'])) {
            alertMes("验证码输入错误！");
            return false;
        } else {
            $data['password'] = md5($data['password']);
            $row = User::where('username', $data['username'])->where('password', $data['password'])->find();
            if ($row) {
                User::save_login_info($data, $row);
                alertMes("验证成功");
                return true;
            } else {
                alertMes("用户名或密码错误！");
                return false;
            }
        }
    }

    /**
     * 保存登录信息
     * @param $data
     * @param $row
     */
    public static function save_login_info($data, $row)
    {
        if (!empty($data['autoFlag']) ? $data['autoFlag'] : null) {
            Cookie::set('userId', $row['id'], 7 * 24 * 3600);
            Cookie::set('userName', $row['username'], 7 * 24 * 3600);
        }
        Session::set('userId', $row['id']);
        Session::set('userName', $row['username']);
    }

    /**
     * 退出登录
     */
    public static function logout()
    {
        Session::delete('userId');
        Session::delete('userName');
        Cookie::delete('userId');
        Cookie::delete('userName');
        Cookie::delete('PHPSESSID');
//        dump(Session::get());
//        dump(Cookie::get());
    }
}