<?php

namespace app\index\controller;

use think\Controller;
use think\Request;
use think\Db;
use app\admin\model\Admin;
use app\admin\model\User;
use app\admin\model\Cate;
use app\admin\model\Pro;
use app\admin\model\Album;

class Index extends Controller
{
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
    }

    public function index()
    {
//        $this->view->engine->layout(true);
        $cates = Cate::all();
        $this->assign('cates', $cates);
        return $this->fetch();
    }

    public function login()
    {
        return $this->fetch();
    }

    public function reg()
    {
        return $this->fetch();
    }

    public function proCate()
    {
        return $this->fetch();
    }

    public function proDetails()
    {
        $request = Request::instance();
        $id = $request->get('id');
        $str = "p.id,p.pName,p.pSn,p.pNum,p.mPrice,p.iPrice,p.pDesc,p.pubTime,p.isShow,p.isHot,c.cName,p.cId";
        $proInfo = Pro::alias('p')->field($str)->join('shop_cate c', 'p.cId=c.id')->where(['p.id' => $id])->find();
        $proImgs=Album::where(['pid'=>$id])->column('albumPath');
        $this->assign('proInfo', $proInfo);
        $this->assign('proImgs', $proImgs);
        $this->assign('id', $id);
//        dump($proImgs);
        return $this->fetch();
    }

    public function shopCar()
    {
        return $this->fetch();
    }

    public function filter()
    {
        return $this->fetch();

    }

    public function _empty()
    {
        return '404';
    }
}
