<?php

namespace app\index\controller;

//use think\View;
use think\Controller;
use app\index\model\User;
use think\Request;
use think\Db;
use think\db\Query;

class Index extends Controller
{
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
    }

    public function index()
    {
        $this->view->engine->layout(true);
        return $this->fetch();
    }

    public function selectUser()
    {
        $user = new User();
        $list = [
            ['username' => 'yang3', 'password' => 'ocean', 'email' => '136494666@qq.com'],
            ['username' => 'yang4', 'password' => 'ocean', 'email' => '136494666@qq.com'],
        ];
        $user->allowField(true)->saveAll($list);
        echo $user->create_time;
        echo $user->update_time;
    }

    public function addUser()
    {
        $user = new User;
        $list = [
            ['username' => 'yang1', 'password' => 'ocean', 'email' => '136494666@qq.com'],
            ['username' => 'yang2', 'password' => 'ocean', 'email' => '136494666@qq.com'],
        ];
        return $user->where('id', 2)->find();
//        return $user->isUpdate()->allowField(true)->saveAll($list);
    }

    public function user()
    {
        /*Db::listen(function($sql, $time, $explain){
            // 记录SQL
            echo $sql. ' ['.$time.'s]';
            // 查看性能分析结果
            dump($explain);
        });*/
//        $query = new Query();
//        return $query->name('admin')->where('id', 2)->select();
//        return dump($query->name('admin')->where('id',2)->select());
//        return dump(Db::getTableInfo('__ADMIN__'));
//        return json(Db::query('select * from shop_admin where id=:id',['id'=>2]));
//        $request = Request::instance();
//        $userId="哈哈";
//        return dump($request->user($userId));
        return $this->fetch('./template/public/index.html');
    }

    public function hello($id = 1)
    {
        return "index模块->hello方法->id=" . $id;
    }

    public function _empty()
    {
        return '404';
    }
}
