<?php
/**
 * Created by PhpStorm.
 * User: ocean
 * Date: 18-1-4
 * Time: 下午8:52
 */

namespace app\index\model;

use think\Model;

class User extends Model
{
    protected $table = 'shop_admin';
    protected $autoWriteTimestamp = 'datetime';
    protected $connection = [
        // 数据库调试模式
        'debug' => true,
        // 是否严格检查字段是否存在
        'fields_strict' => true,
        // 数据集返回类型
//    'resultset_type'  => 'array',
        'resultset_type' => 'collection',
        // 自动写入时间戳字段
        'auto_timestamp' => false,
        // 时间字段取出后的默认时间格式
        'datetime_format' => 'Y-m-d H:i:s',
        // 是否需要进行SQL性能分析
        'sql_explain' => true,
        // 开启断线重连
        'break_reconnect' => true,
    ];

    protected function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
    }
}